import type { Metadata } from "next";
import "../globals.css";
import Navbar from "@/components/Navbar";
import AuthProvider from "@/context/AuthProvider";

export const metadata: Metadata = {
  title: "rentLocals",
  description: "Generated by create next app",
};

export default function MainLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AuthProvider>
      <Navbar />
      {children}
    </AuthProvider>
  );
}
